apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-11-26T05:02:54Z"
  generation: 2
  labels:
    app: uploadservice
  name: uploadservice
  namespace: default
  resourceVersion: "2320774"
  selfLink: /apis/apps/v1/namespaces/default/deployments/uploadservice
  uid: 01680e06-100a-11ea-8fee-42010aa00083
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: uploadservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: uploadservice
    spec:
      containers:
      - image: us.gcr.io/dci-architecture-sbx/upload:latest
        imagePullPolicy: Always
        name: upload
        resources: 
            request:
                cpu: 0.1
                memory: "0.5Gi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2019-11-26T05:02:54Z"
    lastUpdateTime: "2019-11-26T05:02:54Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2019-11-26T05:02:54Z"
    lastUpdateTime: "2019-11-26T05:02:54Z"
    message: ReplicaSet "uploadservice-858f6bdb68" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 2
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1

